server:
  port: 8085

spring:
  application:
    name: patientBill
  data:
    uri: mongodb://localhost:27017/patientbill

# use this while running with locally
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true