server:
  port: 8085

spring:
  application:
    name: patientBill
  data:
    uri: mongodb://mongodb:27017/patientBill

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/