server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1

        - id: planAndExercise
          uri: lb://planAndExercise
          predicates:
            - Path=/api/planAndExercise/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/
