server:
  port: 8084

spring:
  application:
    name: blogForum
  data:
    uri: mongodb://mongodb:27017/blogForum
# use this while running with locally
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# Custom upload settings
app:
  upload:
    dir: uploads
    max-file-size: 5242880  # 5MB in bytes
  # Google Cloud Speech-to-Text Settings
google:
  cloud:
    speech:
      language-code: en-US  # Default language
      encoding: LINEAR16   # Default audio encoding
      sample-rate-hertz: 16000
