server:
  port: 8088

spring:
  application:
    name: notification
  data:
    uri: mongodb://mongodb:27017/notification

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/