server:
  port: 8084

spring:
  application:
    name: blogForum
  data:
    uri: mongodb://mongodb:27017/blogForum

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/