server:
  port: 8092

spring:
  application:
    name: subscription
  data:
    uri: mongodb://mongodb:27017/subscription

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/