server:
  port: 8089

spring:
  application:
    name: event-service
  data:

    mongodb:
      # Use this while running with Docker Compose
      # uri: mongodb://mongodb:27017/eventdb
      uri: mongodb://localhost:27017/eventdb
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


user-service:
  base-url: http://user-service/api/users