server:
  port: 8089

spring:
  task:
    scheduling:
      pool:
        size: 1
  application:
    name: event-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/eventdb
  mail:
    host: smtp.gmail.com
    port: 587
    username: lindabenrhaiem@gmail.com     # Use your email
    password: kooq qrxl fbhw txpi    # Use your app password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

user-service:
  base-url: http://localhost:8081