server:
  port: 8086

spring:
  application:
    name: paramedicalCare
  data:
    uri: mongodb://mongodb:27017/paramedicalCare

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/