server:
  port: 8086

spring:
  application:
    name: paramedicalCare
  data:
    uri: mongodb://localhost:27017/paramedicalCare
google:
  maps:
    api-key: AIzaSyDhJ1QaIMu0XptyDLOUSs1YzQ4SmH7jVG8

  data:
    mongodb:
      auto-index-creation: true # Ensure geospatial index is created
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/