server:
  port: 8086

spring:
  application:
    name: paramedicalCare
  data:
    uri: mongodb://localhost:27017/paramedicalCare

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/