server:
  port: 8082

spring:
  application:
    name: medicalRecord
  data:
    uri: mongodb://localhost:27017/medicalRecord

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/