server:
  port: 8083

spring:
  application:
    name: appointmentAvailability
  data:
    uri: mongodb://localhost:27017/appt
  mail:
    host: smtp.gmail.com
    port: 587
    username: ghassenbelkassem@gmail.com
    password: smldoskgrhkpuqpu # Use an App Password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true