server:
  port: 8091

spring:
  application:
    name: planAndExercise
  data:
    uri: mongodb://localhost:27017/planAndExercise

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/