server:
  port: 8091

spring:
  application:
    name: planAndExercise
  data:
    uri: mongodb://mongodb:27017/planAndExercise  # use the Docker service name 'mongodb'
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/  # use the Docker service name 'service-registry'
