server:
  port: 8091

spring:
  application:
    name: planAndExercise
  data:
    uri: mongodb://localhost:27017/planAndExercise
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

