name: Fast Nexus Test

on:
  push:
    branches:
      - '**'

jobs:
  test-nexus:
    runs-on: self-hosted  # Required for local Nexus access

    steps:
      # --- Checkout first ---
      - name: Checkout Code
        uses: actions/checkout@v3

      # ========== NEXUS TEST (MOVED TO TOP) ==========
      - name: Setup Java for Nexus
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          server-id: nexus
          server-username: ${{ secrets.NEXUS_USERNAME }}
          server-password: ${{ secrets.NEXUS_PASSWORD }}

      # Install Maven explicitly (fixes "mvn not found")
      - name: Install Maven
        run: sudo apt-get update && sudo apt-get install -y maven

      - name: Quick Nexus Deploy Test
        working-directory: careForEldersBack
        run: |
          mvn -v  # Verify Maven installation
          mvn clean deploy -DskipTests -pl user-service  # Test with just one module

      # ========== DOCKER TEST ==========
      - name: Quick Docker Push Test
        run: |
          docker login ${{ secrets.NEXUS_URL }} -u ${{ secrets.NEXUS_USERNAME }} -p ${{ secrets.NEXUS_PASSWORD }}
          docker build -t ${{ secrets.NEXUS_URL }}/quick-test ./careForEldersBack/user-service
          docker push ${{ secrets.NEXUS_URL }}/quick-test
