name: Fullstack CI/CD

on:
  push:
    branches:
      - '**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # --- Checkout code ---
      - name: Checkout Code
        uses: actions/checkout@v3

      # ========== FRONTEND ==========
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Frontend Dependencies
        working-directory: careForEldersFront
        run: npm ci

      - name: Build Angular App
        working-directory: careForEldersFront
        run: npm run build -- --configuration=production --project=testApp

      - name: Docker Build (Frontend)
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/carefrontend ./careForEldersFront

      # ========== BACKEND ==========
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configure Maven to use Maven Central
        run: |
          mkdir -p ~/.m2
          cat <<EOF > ~/.m2/settings.xml
          <settings>
            <mirrors>
              <mirror>
                <id>central</id>
                <mirrorOf>*</mirrorOf>
                <url>https://repo.maven.apache.org/maven2/</url>
              </mirror>
            </mirrors>
          </settings>
          EOF

      - name: Build Backend Services (Maven)
        working-directory: careForEldersBack
        run: mvn clean install -pl user-service,planAndExercise,service-registry,api-gateway -am -DskipTests

      # ========== DOCKER LOGIN ==========
      - name: Docker Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Docker Login to Nexus
        run: echo "${{ secrets.NEXUS_PASSWORD }}" | docker login ${{ secrets.NEXUS_URL }}:5000 -u ${{ secrets.NEXUS_USERNAME }} --password-stdin

      # ========== PUSH DOCKER IMAGES ==========
      ## FRONTEND
      - name: Push Frontend Image to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/carefrontend

      ## BACKEND: DockerHub and Nexus
      - name: Build + Push user-service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/user-service ./careForEldersBack/user-service
          docker push ${{ secrets.DOCKER_USERNAME }}/user-service
          docker tag ${{ secrets.DOCKER_USERNAME }}/user-service ${{ secrets.NEXUS_URL }}:5000/user-service
          docker push ${{ secrets.NEXUS_URL }}:5000/user-service

      - name: Build + Push planAndExercise
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/plan-and-exercise ./careForEldersBack/planAndExercise
          docker push ${{ secrets.DOCKER_USERNAME }}/plan-and-exercise
          docker tag ${{ secrets.DOCKER_USERNAME }}/plan-and-exercise ${{ secrets.NEXUS_URL }}:5000/plan-and-exercise
          docker push ${{ secrets.NEXUS_URL }}:5000/plan-and-exercise

      - name: Build + Push api-gateway
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/api-gateway ./careForEldersBack/api-gateway
          docker push ${{ secrets.DOCKER_USERNAME }}/api-gateway
          docker tag ${{ secrets.DOCKER_USERNAME }}/api-gateway ${{ secrets.NEXUS_URL }}:5000/api-gateway
          docker push ${{ secrets.NEXUS_URL }}:5000/api-gateway

      - name: Build + Push service-registry
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/service-registry ./careForEldersBack/service-registry
          docker push ${{ secrets.DOCKER_USERNAME }}/service-registry
          docker tag ${{ secrets.DOCKER_USERNAME }}/service-registry ${{ secrets.NEXUS_URL }}:5000/service-registry
          docker push ${{ secrets.NEXUS_URL }}:5000/service-registry
