name: Nexus Deployment Test

on:
  push:
    branches:
      - '**'

jobs:
  test-nexus:
    runs-on: self-hosted  # Required for local Nexus access

    steps:
      # --- Checkout ---
      - name: Checkout Code
        uses: actions/checkout@v3

      # --- Java Setup ---
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          server-id: nexus
          server-username: ${{ secrets.NEXUS_USERNAME }}
          server-password: ${{ secrets.NEXUS_PASSWORD }}

      # --- Maven Verification ---
      - name: Verify Tools
        run: |
          java -version
          mvn -v

      # --- Nexus Deployment Test ---
      - name: Deploy to Nexus
        working-directory: careForEldersBack
        run: |
          mvn clean deploy -DskipTests -pl user-service \
          -DaltSnapshotDeploymentRepository=nexus-snapshots::default::${{ secrets.NEXUS_URL }}/repository/maven-snapshots/ \
          -DaltReleaseDeploymentRepository=nexus-releases::default::${{ secrets.NEXUS_URL }}/repository/maven-releases/

      # --- Docker Test ---
      - name: Test Docker Push
        run: |
          docker login ${{ secrets.NEXUS_URL }} \
            -u ${{ secrets.NEXUS_USERNAME }} \
            -p ${{ secrets.NEXUS_PASSWORD }}
          
          docker build -t ${{ secrets.NEXUS_URL }}/user-service-test ./careForEldersBack/user-service
          docker push ${{ secrets.NEXUS_URL }}/user-service-test
