name: Angular Frontend CI/CD

on:
  push:
    branches:
      - '**'


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        working-directory: careForEldersFront
        run: npm ci

      - name: Build Angular App
        working-directory: careForEldersFront
        run: npm run build -- --configuration=production --project=testApp

      - name: Docker Build
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/carefrontend ./careForEldersFront

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/carefrontend
