name: Nexus Deployment Test

on:
  push:
    branches:
      - '**'

jobs:
  test-nexus:
    runs-on: self-hosted  # Required for local Nexus access

    steps:
      # --- Checkout ---
      - name: Checkout Code
        uses: actions/checkout@v3

      # --- Java Setup ---
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # --- Maven Configuration ---
      - name: Configure Maven for Nexus
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<EOF
          <settings>
            <servers>
              <server>
                <id>nexus-releases</id>
                <username>admin</username>
                <password>admin</password>
              </server>
              <server>
                <id>nexus-snapshots</id>
                <username>admin</username>
                <password>admin</password>
              </server>
            </servers>
          </settings>
          EOF

      # --- Nexus Deployment ---
      - name: Deploy to Nexus
        working-directory: careForEldersBack
        run: |
          mvn clean deploy -DskipTests -pl user-service \
          -DaltReleaseDeploymentRepository=nexus-releases::default::http://10.0.2.15:8090/repository/maven-releases/ \
          -DaltSnapshotDeploymentRepository=nexus-snapshots::default::http://10.0.2.15:8090/repository/maven-snapshots/

      # --- Docker Test ---
      - name: Test Docker Push
        run: |
          docker login http://10.0.2.15:8090 \
            -u admin \
            -p your_admin_password
          
          docker build -t 10.0.2.15:8090/user-service-test ./careForEldersBack/user-service
          docker push 10.0.2.15:8090/user-service-test
