name: Fullstack CI/CD with Nexus

on:
  push:
    branches:
      - '**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # --- Checkout code ---
      - name: Checkout Code
        uses: actions/checkout@v3

      # ========== FRONTEND ==========
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Frontend Dependencies
        working-directory: careForEldersFront
        run: npm ci

      - name: Build Angular App
        working-directory: careForEldersFront
        run: npm run build -- --configuration=production --project=testApp

      # ========== BACKEND ==========
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          server-id: nexus
          server-username: ${{ secrets.NEXUS_USERNAME }}
          server-password: ${{ secrets.NEXUS_PASSWORD }}

      - name: Build and Deploy to Nexus
        working-directory: careForEldersBack
        run: |
          mvn clean deploy -DskipTests
          mvn clean install -pl user-service,planAndExercise,service-registry,api-gateway -am -DskipTests

      # ========== DOCKER IMAGES TO NEXUS ==========
      - name: Login to Nexus Docker Registry
        run: |
          echo "${{ secrets.NEXUS_PASSWORD }}" | docker login ${{ secrets.NEXUS_URL }} -u ${{ secrets.NEXUS_USERNAME }} --password-stdin

      - name: Build and Push Docker Images
        run: |
          # Build and push each service
          services=("user-service" "planAndExercise" "api-gateway" "service-registry")
          for service in "${services[@]}"; do
            docker build -t ${{ secrets.NEXUS_URL }}/$service ./careForEldersBack/$service
            docker push ${{ secrets.NEXUS_URL }}/$service
          done

          # Frontend image
          docker build -t ${{ secrets.NEXUS_URL }}/carefrontend ./careForEldersFront
          docker push ${{ secrets.NEXUS_URL }}/carefrontend
