name: Fullstack CI/CD

on:
  push:
    branches:
      - '**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # --- Checkout code ---
      - name: Checkout Code
        uses: actions/checkout@v3

      # ========== FRONTEND ==========
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Frontend Dependencies
        working-directory: careForEldersFront
        run: npm ci

      - name: Build Angular App
        working-directory: careForEldersFront
        run: npm run build -- --configuration=production --project=testApp

      - name: Docker Build (Frontend)
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/carefrontend ./careForEldersFront

      # ========== BACKEND ==========
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Backend Services (Maven)
        working-directory: careForEldersBack
        run: mvn clean install -pl user-service,planAndExercise,service-registry,api-gateway -am -DskipTests


      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # --- Push All Docker Images ---
      - name: Push Frontend Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/carefrontend

      - name: Build + Push user-service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/user-service ./careForEldersBack/user-service
          docker push ${{ secrets.DOCKER_USERNAME }}/user-service

      - name: Build + Push planAndExercise
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/plan-and-exercise ./careForEldersBack/planAndExercise
          docker push ${{ secrets.DOCKER_USERNAME }}/plan-and-exercise

      - name: Build + Push api-gateway
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/api-gateway ./careForEldersBack/api-gateway
          docker push ${{ secrets.DOCKER_USERNAME }}/api-gateway

      - name: Build + Push service-registry
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/service-registry ./careForEldersBack/service-registry
          docker push ${{ secrets.DOCKER_USERNAME }}/service-registry
